//NOTE: This is just a template to copy-paste into my TOP module that wires up
// with DE0-Nano ports. It was generated by the ALTPLL IP MegaWizard in Quartus,
// to implement a PLL.
pll	pll_inst (
	.inclk0 ( inclk0_sig ),
	.c0 ( c0_sig )
	);
